"""
Nexora Platform — GrowthAI Campaign Management ORM Models
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Uuid
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel


class MarketingCampaign(BaseModel):
    """
    Marketing Campaigns Table.
    Groups strategies, audiences, and assets generated by GrowthAI agents.
    """

    __tablename__ = "marketing_campaigns"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    target_audience: Mapped[str | None] = mapped_column(nullable=True)
    strategy_description: Mapped[str | None] = mapped_column(nullable=True)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="draft", index=True)

    # Relationships
    posts: Mapped[list[SocialPost]] = relationship(
        "SocialPost",
        back_populates="campaign",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<MarketingCampaign(id={self.id}, name={self.name}, status={self.status})>"


class SocialPost(BaseModel):
    """
    Social Posts Table.
    Maintains generated content drafts scheduled for deployment on external channels.
    """

    __tablename__ = "social_posts"

    campaign_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("marketing_campaigns.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False)  # facebook, instagram, linkedin, etc.
    content_draft: Mapped[str] = mapped_column(nullable=False)
    language: Mapped[str] = mapped_column(String(10), nullable=False, default="en")
    scheduled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending", index=True)
    external_post_id: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships
    campaign: Mapped[MarketingCampaign] = relationship("MarketingCampaign", back_populates="posts")

    def __repr__(self) -> str:
        return f"<SocialPost(id={self.id}, platform={self.platform}, status={self.status})>"


class ContentLibrary(BaseModel):
    """
    Content Library Table.
    A database of templates, raw copy suggestions, and media vectors used to prompt campaigns.
    """

    __tablename__ = "content_library"

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(nullable=False)
    media_file_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("files.id"),
        nullable=True,
    )
    tags: Mapped[list[str] | None] = mapped_column(ARRAY(String(100)), nullable=True)

    def __repr__(self) -> str:
        return f"<ContentLibrary(id={self.id}, title={self.title})>"
